### ISSUE TITLE
Method of an IDL interface returning an Object or interface type

### ISSUE THREAD

**Issue by okellogg** [AdaCore/PolyORB#23]
Hi,

Suppose we have a method of an interface returning an `Object` or interface type, [such as](compilers/idlac/testsuite/mapping/arg.idl)

```
interface all_types {
  Object echo12(in Object arg);
};  
```

then the echo12 method is mapped as follows:
```
   function echo12
     (Self : Ref;
      arg : CORBA.Object.Ref)
     return CORBA.Object.Ref;
```

I find it questionable whether this is what the user expects because the method dispatches on its return type.

[GNACK](https://sourceforge.net/p/orbitada/gnack/ci/master/tree/) maps this as
```
   procedure echo12
     (Self : in Ref;
      arg : in CORBA.Object.Ref'Class;
      Returns : out CORBA.Object.Ref'Class);
```

The way PolyORB maps it is actually according to the IDL to Ada mapping standard.
Before raising an issue at OMG, I would be interested in your opinion on this matter.

**Comment by ArnaudCharlet** [comment]
Hi Oliver, thank you for raising this issue.
At this stage we want to favor stability and keep the status quo and some level of convenience for users, even though as you said the dispatching on return type might lead to unexpected cases. Have you actually encountered such cases in practice though?. Probably if we were starting from scratch, it would be worth considering your point.
Take care!

**Comment by okellogg** [comment]
Hi Arnaud,

> Have you actually encountered such cases in practice though?

Yes, in fact that was the basis for this question:
https://sourceforge.net/p/orbitada/discussion/153514/thread/05276d926a/#b960/8773

Thanks for your attention,

Oliver

**Comment by sttaft** [comment]
Hi Oliver,
    Can you explain the problem you had which you said involve dispatching on return type?  Based on the example, it appears the only controlling operand is the "Self" parameter, and the function is not dispatching on its return type.  I am presuming the echo12 function is not itself declared in CORBA.Obj, and the function always returns the specific type, CORBA.Obj.Ref.   Arnaud brought this to my attention, so I am trying to understand whether this actually relates to dispatching on result.

Thanks,
-Tucker Taft
AdaCore
Lexington, MA

**Comment by okellogg** [comment]
Hello Tucker,

You are right, the example using CORBA.Object was not good for showing the problem.
Instead, I should have used a user defined interface.
I will open a new ticket in a few days.

Many thanks,
Oliver

**Comment by sttaft** [comment]
OK, thanks.  I'll be interested in the new example.

Take care,
-Tuck

**Comment by okellogg** [comment]
Hello,

> Instead, I should have used a user defined interface.

I had another look at the [IDL to Ada mapping standard](https://www.omg.org/spec/ADA/1.3/PDF) and in **9.5.4 Mapping for Operations** found

> Arguments or result types of the enclosing IDL unit type shall be mapped to the class of the mapped reference type (for example, to Ref’CLASS for unconstrained interfaces).
> This is necessary to prevent multiple controlling parameters (it removes the ambiguity as to which parameter controls
> dispatching.)

I believe that my problem resulted from not applying that rule.
For example, given the following excerpt from [CosNaming.idl](https://github.com/AdaCore/PolyORB/blob/master/idls/cos/naming/CosNaming.idl):
```
    interface NamingContext {
        NamingContext new_context ();
    };
```
PolyORB maps the `new_context` operation as follows:
```
   function New_Context
     (Self : Ref)
     return CosNaming.NamingContext.Ref'Class;
```
whereas the workaround in GNACK was made on the basis of:
```
   function New_Context (Self : Ref) return CosNaming.NamingContext.Ref;
```
Notice the missing `'Class` on the return value.
I will look again after fixing the code generation in GNACK.

**Comment by okellogg** [comment]
Hello Tucker,

I had written:

> Instead, I should have used a user defined interface.
> I will open a new ticket in a few days.

This turned out to be a problem in GNACK, not in the Ada mapping standard.

After fixing the [code generation](https://sourceforge.net/p/orbitada/gnack/commit_browser), the problem with [CosNaming](https://sourceforge.net/p/orbitada/gnack/ci/master/tree/tests/cosnaming) disappeared.

Many thanks for your comment on this issue,

Oliver

**Comment by ArnaudCharlet** [comment]
Great, thanks for letting us know and glad to know that this was a false alarm!
