### ISSUE TITLE
polyorb-dsa_p-storages-dfs.adb:426:37: warning: "Success" modified by call, but value might not be referenced

### ISSUE THREAD

**Issue by Medhu** [AdaCore/PolyORB#31]
Hi! 
Using Windows 11
I have downloaded and install GNAT from AdaCore:

gnat --version gives 

GNAT Community 2020 (20200818-93)
Copyright (C) 1996-2020, Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I have cloned with:
git clone https://github.com/AdaCore/PolyORB

$ polyorb-config --version
./polyorb-config: line 41: cygpath: command not found
PolyORB 20.0w (rev. 79b8aa71) for i686-pc-mingw32

In MinGW I perform:
support/reconfig

./configure -prefix=c:/GNAT/2020 --with-appli-perso="corba dsa moma" --with-proto-perso="giop soap srp" --with-corba-services="event ir naming notification time" --with-openssl --with-gnatcoll

make top_builddir=c:/Ada/Git/PolyORB

The builds for a while, then ends in this error:

   [Ada]          polyorb-dsa_p-streams.adb
   [Ada]          polyorb-dsa_p-storages.adb
   [Ada]          polyorb-dsa_p-storages-dsm.adb
   [Ada]          polyorb-dsa_p-storages-dfs.adb
   [Ada]          polyorb-dsa_p-storages-config.adb
   [Ada]          polyorb-dsa_p-remote_launch.adb
   [Ada]          polyorb-dsa_p-partitions.adb
   [Ada]          polyorb-dsa_p-name_service.adb
   [Ada]          polyorb-dsa_p-name_service-none.adb
   [Ada]          polyorb-dsa_p-name_service-mdns.adb
   [Ada]          polyorb-dsa_p-name_service-mdns-servant.adb
   [Ada]          polyorb-dsa_p-name_service-mdns-helper.adb
**polyorb-dsa_p-storages-dfs.adb:426:37: warning: "Success" modified by call, but value might not be referenced**

   compilation of polyorb-dsa_p-storages-dfs.adb failed

gprbuild: *** compilation phase failed
make: *** [polyorb_src_dsa.gpr] Error 5

The error refers to this snippet of code;

   ----------
   -- Lock --
   ----------

   overriding procedure Lock (Self : access DFS_Manager_Type) is
      Success : Boolean;

   begin
      Enter (Self.PO_Mutex);
      Initiate_Request (Self, Lock, Success);
   end Lock;

In a previous version of the file polyorb-dsa_p-storages-dfs.adb there has been a :
"pragma Unreferenced (Success)".

Any advice? I might add the pragma in my local version, but I don't know if that in some way will cause any other problem.

Frank Jørgensen

**Comment by godunko** [comment]
Hello,

It is safe to add pragma Unreferenced (Success), it is required for old compilers only.
