### ISSUE TITLE
Missing files for server generation from iac

### ISSUE THREAD

**Issue by FredPraca** [AdaCore/PolyORB#7]
Suppose we use the following IDL file
```idl
module my_module
{

  interface my_interface
  {
    string helloWorld();
  };
};
```
And that we want  to keep server and client development separated using the following structure
```
.
├── client
├── server
└── test.idl
```

Using the command ` iac -o server -i -s test.idl`, we get the following files:
*  my_module_my_interface_hash.adb
* my_module_my_interface_hash.ads
* my_module-my_interface-impl.adb
* my_module-my_interface-impl.ads
* my_module-my_interface-skel.adb
* my_module-my_interface-skel.ads

Then we create a main unit which is the server that will hold our servant, i.e. our object implementation.

When trying to compile the project,  a compilation error is thrown, `server.adb:17:06: file "my_module.ads" not found`.

The problem is that this file is only created when calling _iac_ for the client part but not the server part even though, it's required to compile the server part too.

**Comment by FredPraca** [comment]
Of course, after generating the missing file for the module using the client part of _iac_, the spec and the body for the interface are also missing.
I think that these three files should be generated also when creating only server files.

**Comment by quinot** [comment]
What you want is use "-c" for the client case and no command line switch for the server case. The "client" units are really common to the client and server cases, as you noted.

Note that the *-impl units are meant to be filled by the application developer with the actual implementation of interfaces, so we recommend that care be used with the use of the "-i" command line switch (which will obviously lose all of these customizations and regenerate empty implementation templates).

**Comment by FredPraca** [comment]
Does it mean that _-s_ should not exist at all ?
What is its purpose in this case ?
That's the reason why I asked if it would be possible to generate spec and body for the module and interface IDL code. Without having something usable using _-s_ flag, its use becomes useless.

Moreover, I thought that it would be more comprehensive to forbid the use of _-i_ in conjunction with _-c_ as implementation codes are for server only.
And Yes, using _-i_ is tricky and surprising as I learned it several years ago :smiley:.

**Comment by quinot** [comment]
The rationale for -s is to avoid regenerating the common part if the regeneration will only change the server part (e.g. when using different iac command line switches that only affect the server side).
At this stage our focus is mostly on preserving backwards compatibility, so we'd rather not change the meaning of command line switches unless there's a compelling error to fix.

**Comment by FredPraca** [comment]
Thanks for the clarification
